/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2024-11-07 01:52:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._11JSTL.core;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.StringTokenizer;

public final class ForTokens_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/workspace/JSPStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSPServlet/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1730767805537L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.StringTokenizer");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JSTL - forTokens</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \r\n");
      out.write("forTokens 태그 : 문자열에서 특정 구분자를 통해 반환된 배열의 크기만큼 반복해야할때 사용한다.\r\n");
      out.write("속성]\r\n");
      out.write("	items : 구분자를 포함한 문자열을 지정한다. 컬렉션이나 배열은 사용할 수 없다.\r\n");
      out.write("	delims(Delimiter) :  구분자. 여러가지 특수기호('-', '콤마', '/', ';')를 사용할 수 있다.\r\n");
      out.write("	var : 구분자를 통해 잘라낸 토큰을 저장한다.\r\n");
      out.write("	* 토큰이란? :문법적으로 의미있는 최소단위. 하이픈으로 구분되는 전화번호를 분리했을때 각 번호가 토큰. \r\n");
      out.write("	-->\r\n");
      out.write("	");

	String rgba = "Red, Green, Blue, Black";
	
      out.write("\r\n");
      out.write("	<h4>JSTL의 forTokens태그 사용</h4>\r\n");
      out.write("	<!-- 콤마를 기준으로 문자열을 잘라낸 뒤 하나씩 출력한다. -->\r\n");
      out.write("	");
      //  c:forTokens
      org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
      _jspx_th_c_005fforTokens_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f0.setParent(null);
      // /11JSTL/core/ForTokens.jsp(25,1) name = items type = jakarta.el.ValueExpression reqTime = true required = true fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setItems( rgba );
      // /11JSTL/core/ForTokens.jsp(25,1) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setDelims(",");
      // /11JSTL/core/ForTokens.jsp(25,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setVar("color");
      int[] _jspx_push_body_count_c_005fforTokens_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f0 = _jspx_th_c_005fforTokens_005f0.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<span style=\"color:");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(';');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fdelims.reuse(_jspx_th_c_005fforTokens_005f0);
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforTokens_005f0, _jsp_getInstanceManager());
      out.write("\r\n");
      out.write("	<h4>StringTokenizer 클래스 사용</h4>\r\n");
      out.write("	");

	StringTokenizer tokens = new StringTokenizer(rgba, ",");
	out.print("토큰 수 : "+tokens.countTokens()+"<br/>");
	while(tokens.hasMoreTokens()){
		String t = tokens.nextToken();
		out.print(t);
	}
	
      out.write("\r\n");
      out.write("	<h4>String클래스의 split메서드 사용</h4>\r\n");
      out.write("	");

	String[] colorArr = rgba.split(",");
	for(String color:colorArr){
		out.print(color + "<br/>");
	}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
